### ISSUE TITLE
Don't include 25MB files in a git repository where possible

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#328]
Especially without documentation

https://github.com/peq/WurstScript/blob/f14f472657b004be2915e2dbaa898f625be86e44/de.peeeq.wurstscript/testscripts/valid/optimizer/test.wurst

Introduced in commit: f655fad9

**Comment by peq** [comment]
I think this file was included by accident and I am too afraid to rewrite the history. There are also some other big files in the repository. Maybe it would be a good ideas to split the repository, e.g. have Wurstpack in a separate one. And then also use dependency management instead of putting the jar files directly into git.

It's just a rather boring task, so I am not sure whether I will do it :D

**Comment by Frotty** [comment]
@peq could use gradle

**Comment by blakehawkins** [comment]
@peq there's no need to rewrite the history, just remove the file from the repository now. Later when this is a sufficiently old and the repository size actually begins to be an issue you can trim it.

Large snapshot histories are better than large repositories.

**Comment by Cokemonkey11** [comment]
@peq there's no need to rewrite the history, just remove the file from the repository now. Later when this is sufficiently old and the repository size actually begins to be an issue you can trim it.

Large snapshot histories are better than large repositories.
