### ISSUE TITLE
Don't import public imports unless they are used (or similar solution)

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#377]
I have addressed this a few times now: When saving an empty map, wurst still puts a lot of code inside the war3map.j from public StdLib imports-chains like Camera.
This way the script file has about 750 lines instead of needed 200 lines (unoptimized).

~~Many globals in the final output aren't even being read nor written to, yet they aren't being removed?~~
Didn't know I had to activate the Inliner for the variables to get removed.
Anyways, the stuff gets all jammed into 1 function and locals - even though none of these are used and could just be removed.
Or we need something to init standard.packages only when used

**Comment by peq** [comment]
The problem is that we have too many public imports in `wurst.wurst`. But changing that now would mean breaking a lot of old code.

Maybe if I add quickfixes for adding imports it would be possible to remove the public imports from the standard library, because then old code could mostly be fixed automatically.

Another option would be to decouple the standard library from the compiler. That way people could keep the old standard library for their old maps and we would be free to upgrade the standard library.

**Comment by Frotty** [comment]
a958281a5e5f6cc11cf3f52e511a9eb01e002297 removed some garbage, but global arrays are still kept.
Example 
````
Char.wurst
string array c2s
````

**Comment by Cokemonkey11** [comment]
Related : #322
