### ISSUE TITLE
Inliner not inling functions

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#386]
See for example https://github.com/Frotty/ForestDef/blob/master/wurst/_abstract/entity/PhysicsEntity.wurst
````
inAir
````
is inlined,
````
onGround
````
not.
Yet they are both only used once in the above function
````
physicsUpdate
````

**Comment by peq** [comment]
The `onGround` function has a return statement which is not at the end. Currently functions can only be inlined when there is only one return statement at the end.

To implement inlining for functions with multiple returns, it would be necessary to automatically rewrite the function to only one return. This would be easy if Jass had goto statements or if efficiency would not be important. 

If there are no loops it can be done with a fake-loop and `exitwhen` statements. When there are loops it could be done with additional boolean variables. However, I am not sure if this is worth the effort. It would also need some benchmarking, because loops and additional variables probably have some cost as well...
