### ISSUE TITLE
Eclipse plugin considers this (necessary) lambda cast as an unused variable

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/WurstScript#422]
![image](https://cloud.githubusercontent.com/assets/1418966/11015612/b1b78548-855c-11e5-8e05-4ea7e045e9ab.png)

**Comment by peq** [comment]
This is not a cast, `cb` is the parameter of the lambda. If you do not use the variable, prefix it with an underscore to suppress the warning.

**Comment by Cokemonkey11** [comment]
@peq that's totally a bug, but do what you want

**Comment by peq** [comment]
You don't use the variable and you get a warning that it is not used. I do not see how this is a bug...

**Comment by Cokemonkey11** [comment]
I am using it as a parameter to `doPeriodically`. Without it, I cannot use `doPeriodically`.

**Comment by peq** [comment]
The warning is supposed to help you. In most cases it is a mistake if a variable is not used. And as I said, you can just add an underscore to the beginning of the variable name, if you decide not to use it. This also makes the intend clear to readers of your code.

By the way: The CallBackPeriodic parameter is there for a reason. If you are not using it, you could use a different function which does not have the functionality to cancel the periodic event. In your case a simple timer would be enough and more efficient, since you are not even capturing any local variables in your closure.

**Comment by Cokemonkey11** [comment]
> By the way: The CallBackPeriodic parameter is there for a reason. If you are not using it, you could use a different function which does not have the functionality to cancel the periodic event. In your case a simple timer would be enough and more efficient, since you are not even capturing any local variables in your closure.

You're absolutely right - I've just changed that code to reflect this. I think as long as I don't have a good and necessary example of using `doPeriodically` without using the `CallbackPeriodic`, this can be case closed.

For the record though, this is the part I don't like:

> And as I said, you can just add an underscore to the beginning of the variable name, if you decide not to use it. This also makes the intend clear to readers of your code.

**Comment by peq** [comment]
What exactly don't you like about this? The only other options that I can think of are:

1. Remove the warning for parameters, or only for closure parameters. *I don't like this, because I think in most cases the warning is useful and it can be easily suppressed.*
2. Change the syntax for suppressing warnings. *I like the current syntax and it is used by some other languages. I think something like Javas `@SuppressWarnings("unused")` is too long.*

**Comment by Crigges** [comment]
I think there are a lot cases where you don't want to have control over a periodic action. Maybe we can add a version of ```doPeriodically``` which closure does not need paramters, just like for ```doAfter```.

**Comment by Cokemonkey11** [comment]
> Change the syntax for suppressing warnings. I like the current syntax and it is used by some other languages. I think something like Javas @SuppressWarnings("unused") is too long.

I would prefer something like this. I think annotations are a more powerful and general purpose tool. I think that the current configuration arbitrarily couples the LINT software with the program code. There shouldn't be a LINT guideline like "prefix unused variables with underscore" because unused variables shouldn't be used at all, which brings me to:

> I think there are a lot cases where you don't want to have control over a periodic action. Maybe we can add a version of doPeriodically which closure does not need paramters, just like for doAfter.

I think this is absolutely the right thing., so :+1: from me
