### ISSUE TITLE
Inliner endless loop/stackoverflow

### ISSUE THREAD

**Issue by Frotty** [peq/WurstScript#510]
log: https://hastebin.com/raviqedeza.go
It happens with EBR(d0a6537)+Frentity(509ddca)+Stdlib2(f42cca2) at those commits and flags enabled as shown in log.

**Comment by Frotty** [comment]
blocker weil ebr ohne inliner nicht startet,

**Comment by peq** [comment]
There is some crazy stuff in there with the big strings and LZW. I have to dig further into this to find the root cause, but the fix above should make sure that it terminates. However, this bug is already a hint, that this probably generates some very complex code, which we might have to optimize in other ways.

**Comment by Frotty** [comment]
lep suggested this fix: 
````
ImLiner.java:85
for (int i = parentI; i < e.size(); i++) {
````

And it also worked.
Which change is better? Yours terminates now at fixed 5? nestings. Does lep's solution omit some inlienable code?

And yeah, the string manipulation is getting quite complex.

**Comment by peq** [comment]
I think leps solution would ommit some optimizations completely and not fix the termination issue. `parentI` is the postion of e in parent and has nothing to do with `e.size()`.

At some point I should spend the time to do a real inliner.
